default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: doc_chase_development

test:
  <<: *default
  database: doc_chase_test

production:
  <<: *default
  database: doc_chase_production
  username: doc_chase
  password: <%= ENV['APP_NAME_DATABASE_PASSWORD'] %>
